# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sIClvSM1p6ReK1MHIpW49AnA1G5cRaF2
"""

import json
import torch
import torch.nn as nn
import gradio as gr
from PIL import Image
from torchvision import models, transforms


# =========================
# CONFIG
# =========================
class CFG:
    IMG_SIZE = 224
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


# =========================
# TRANSFORM
# =========================
def get_inference_transform():
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]

    return transforms.Compose([
        transforms.Resize((CFG.IMG_SIZE, CFG.IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize(mean, std),
    ])


# =========================
# MODEL
# =========================
class ResNet18Emotion(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        self.backbone = models.resnet18(weights=None)
        in_features = self.backbone.fc.in_features
        self.backbone.fc = nn.Linear(in_features, num_classes)

    def forward(self, x):
        return self.backbone(x)


# =========================
# LOAD ASSETS
# =========================
with open("class_names.json", "r") as f:
    CLASS_NAMES = json.load(f)

model = ResNet18Emotion(num_classes=len(CLASS_NAMES))
model.load_state_dict(torch.load("best_model.pth", map_location=CFG.DEVICE))
model.to(CFG.DEVICE)
model.eval()

transform = get_inference_transform()


# =========================
# INFERENCE
# =========================
def predict_emotion(image):
    if image is None:
        return (
            None,
            {"No image": 1.0},
            """
            <div class="result-placeholder">
                <div class="pulse-icon">🫥</div>
                <h3>No analysis yet</h3>
                <p>Upload an image to begin emotion detection</p>
            </div>
            """
        )

    image = image.convert("RGB")
    x = transform(image).unsqueeze(0).to(CFG.DEVICE)

    with torch.no_grad():
        logits = model(x)
        probs = torch.softmax(logits, dim=1)[0]

    pred_idx = torch.argmax(probs).item()
    pred_label = CLASS_NAMES[pred_idx]
    confidence = float(probs[pred_idx].item())

    result = {
        CLASS_NAMES[i].capitalize(): float(probs[i].item())
        for i in range(len(CLASS_NAMES))
    }

    pretty_label = pred_label.capitalize()

    summary_html = f"""
    <div class="result-card">
        <div class="result-badge">Prediction</div>
        <h2>{pretty_label}</h2>
        <div class="confidence-row">
            <span>Confidence</span>
            <span>{confidence:.2%}</span>
        </div>
        <div class="confidence-bar">
            <div class="confidence-fill" style="width:{confidence * 100:.1f}%"></div>
        </div>
        <div class="mini-note">
            The model analyzed the uploaded facial image and predicted the dominant emotion class.
        </div>
    </div>
    """

    return image, result, summary_html


def reset_ui():
    return (
        None,
        {"No image": 1.0},
        """
        <div class="result-placeholder">
            <div class="pulse-icon">🫥</div>
            <h3>No analysis yet</h3>
            <p>Upload an image to begin emotion detection</p>
        </div>
        """
    )


# =========================
# CSS
# =========================
CUSTOM_CSS = """
:root {
    --bg: #eef3fb;
    --card: rgba(255,255,255,0.88);
    --card-border: rgba(96, 125, 255, 0.12);
    --text: #0f172a;
    --muted: #64748b;
    --primary: #2563eb;
    --primary-2: #4f46e5;
    --accent: #60a5fa;
    --shadow: 0 10px 30px rgba(37, 99, 235, 0.10);
    --radius: 22px;
}

.gradio-container {
    max-width: 1280px !important;
    margin: 0 auto !important;
    background: linear-gradient(180deg, #edf3ff 0%, #f7faff 100%) !important;
}

body {
    background: linear-gradient(180deg, #edf3ff 0%, #f7faff 100%) !important;
}

.main-wrap {
    padding: 10px 6px 28px 6px;
}

.hero {
    background: linear-gradient(135deg, #2563eb 0%, #1d4ed8 45%, #4338ca 100%);
    border-radius: 28px;
    padding: 28px 32px;
    color: white;
    box-shadow: 0 18px 40px rgba(37, 99, 235, 0.28);
    margin-bottom: 22px;
}

.hero-title {
    display: flex;
    align-items: center;
    gap: 14px;
    font-size: 2rem;
    font-weight: 700;
    line-height: 1.1;
}

.hero-icon {
    width: 54px;
    height: 54px;
    border-radius: 16px;
    background: rgba(255,255,255,0.16);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.5rem;
    backdrop-filter: blur(8px);
}

.hero-sub {
    margin-top: 8px;
    color: rgba(255,255,255,0.86);
    font-size: 1rem;
}

.section-card {
    background: var(--card) !important;
    border: 1px solid var(--card-border) !important;
    border-radius: var(--radius) !important;
    box-shadow: var(--shadow) !important;
    padding: 10px !important;
    backdrop-filter: blur(10px);
}

.card-title {
    font-size: 1rem;
    font-weight: 700;
    color: var(--text);
    margin-bottom: 6px;
}

.card-subtitle {
    color: var(--muted);
    font-size: 0.94rem;
    margin-bottom: 10px;
}

.upload-box, .result-box {
    min-height: 430px;
}

.info-box {
    min-height: 210px;
}

.result-placeholder {
    height: 100%;
    min-height: 290px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    color: #64748b;
    text-align: center;
    padding: 24px;
}

.result-placeholder h3 {
    margin: 8px 0 4px 0;
    color: #334155;
}

.result-placeholder p {
    margin: 0;
    font-size: 0.95rem;
}

.pulse-icon {
    width: 72px;
    height: 72px;
    border-radius: 999px;
    background: linear-gradient(135deg, #dbeafe 0%, #e0e7ff 100%);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.8rem;
    margin-bottom: 12px;
}

.result-card {
    background: linear-gradient(180deg, rgba(255,255,255,0.95), rgba(245,248,255,0.95));
    border: 1px solid rgba(96,125,255,0.15);
    border-radius: 20px;
    padding: 18px;
    box-shadow: 0 8px 25px rgba(37, 99, 235, 0.08);
}

.result-badge {
    display: inline-block;
    padding: 7px 12px;
    border-radius: 999px;
    background: linear-gradient(135deg, #dbeafe, #e0e7ff);
    color: #1d4ed8;
    font-size: 0.83rem;
    font-weight: 700;
    margin-bottom: 8px;
}

.result-card h2 {
    margin: 4px 0 14px 0;
    color: #0f172a;
    font-size: 1.8rem;
}

.confidence-row {
    display: flex;
    justify-content: space-between;
    font-weight: 600;
    color: #334155;
    margin-bottom: 8px;
}

.confidence-bar {
    width: 100%;
    height: 12px;
    border-radius: 999px;
    background: #e2e8f0;
    overflow: hidden;
    margin-bottom: 14px;
}

.confidence-fill {
    height: 100%;
    border-radius: 999px;
    background: linear-gradient(90deg, #2563eb, #4f46e5);
}

.mini-note {
    color: #64748b;
    font-size: 0.94rem;
    line-height: 1.55;
}

.feature-list {
    margin: 10px 0 0 0;
    padding-left: 18px;
    color: #334155;
}

.feature-list li {
    margin-bottom: 8px;
}

.footer-note {
    margin-top: 14px;
    text-align: center;
    color: #64748b;
    font-size: 0.92rem;
}

button.primary {
    background: linear-gradient(135deg, #2563eb, #4f46e5) !important;
    border: none !important;
}

button.secondary {
    border-radius: 14px !important;
}

.gr-button {
    border-radius: 14px !important;
}

.gr-box, .gr-panel {
    border: none !important;
}

@media (max-width: 900px) {
    .hero-title {
        font-size: 1.55rem;
    }
}
"""


# =========================
# UI
# =========================
with gr.Blocks(css=CUSTOM_CSS, theme=gr.themes.Soft()) as demo:
    gr.HTML("""
    <div class="main-wrap">
        <div class="hero">
            <div class="hero-title">
                <div class="hero-icon">😊</div>
                <div>Facial Emotion Detector</div>
            </div>
            <div class="hero-sub">
                AI-powered facial emotion analysis using a fine-tuned ResNet18 model trained on FER2013.
            </div>
        </div>
    </div>
    """)

    with gr.Row():
        with gr.Column(scale=5):
            with gr.Group(elem_classes="section-card upload-box"):
                gr.Markdown("### Media Upload")
                gr.Markdown("Upload a facial image and analyze the dominant emotion.")

                image_input = gr.Image(
                    type="pil",
                    label=None,
                    height=300
                )

                with gr.Row():
                    analyze_btn = gr.Button("Analyze", variant="primary")
                    reset_btn = gr.Button("Reset")

        with gr.Column(scale=5):
            with gr.Group(elem_classes="section-card result-box"):
                gr.Markdown("### Analysis Results")
                result_html = gr.HTML("""
                <div class="result-placeholder">
                    <div class="pulse-icon">🫥</div>
                    <h3>No analysis yet</h3>
                    <p>Upload an image to begin emotion detection</p>
                </div>
                """)
                output_label = gr.Label(
                    label="Emotion Probabilities",
                    num_top_classes=7
                )
                preview_image = gr.Image(
                    type="pil",
                    label="Preview",
                    height=220
                )

    with gr.Row():
        with gr.Column(scale=4):
            with gr.Group(elem_classes="section-card info-box"):
                gr.Markdown("### Project Description")
                gr.HTML("""
                <div class="mini-note">
                    This system uses a deep convolutional neural network to classify facial expressions
                    into seven emotional categories. It is designed as a clean demo app for fast image-based emotion analysis.
                </div>
                """)

        with gr.Column(scale=4):
            with gr.Group(elem_classes="section-card info-box"):
                gr.Markdown("### Objectives")
                gr.HTML("""
                <ul class="feature-list">
                    <li>Detect dominant emotion from uploaded face images</li>
                    <li>Return confidence-based class probabilities</li>
                    <li>Provide a simple and modern interactive UI</li>
                    <li>Enable quick local and cloud deployment</li>
                </ul>
                """)

        with gr.Column(scale=4):
            with gr.Group(elem_classes="section-card info-box"):
                gr.Markdown("### Methodology")
                gr.HTML("""
                <ul class="feature-list">
                    <li>FER2013 dataset-based training pipeline</li>
                    <li>Transfer learning with ResNet18 backbone</li>
                    <li>PyTorch inference with softmax probabilities</li>
                    <li>Gradio frontend for deployment on Hugging Face Spaces</li>
                </ul>
                """)

    gr.HTML("""
    <div class="footer-note">
        Best suited for face-centered images. Performance may drop on full-scene or uncropped photos.
    </div>
    """)

    analyze_btn.click(
        fn=predict_emotion,
        inputs=image_input,
        outputs=[preview_image, output_label, result_html]
    )

    reset_btn.click(
        fn=reset_ui,
        inputs=[],
        outputs=[image_input, output_label, result_html]
    )

#Celal Ibrahimli
demo.launch()